version: "3.7"
services:
  backend:
    image: registry.gitlab.com/turniere/turniere-backend/development
    container_name: turniere-backend
    ports:
      - "3000:3000" 
  frontend:
    image: registry.gitlab.com/turniere/turniere-frontend:master
    container_name: turniere-frontend
    environment:
      - TURNIERE_API_URL=http://localhost:3000
    ports:
      - "80:80" 
